# Generated by Django 3.2.9 on 2021-11-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=126)),
                ('data_nascimento', models.DateField(null=True)),
                ('ativo', models.BigIntegerField(default=True)),
            ],
        ),
    ]
