# Generated by Django 3.2.9 on 2021-11-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_contato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='Pessoa',
            new_name='pessoa',
        ),
    ]
